"""
Generate 4-section markdown reports for any signal pair.

Template structure (per feedback_backtest_methodology.md):
  Section 1 — Data collection (sources, URLs, ranges, sample data)
  Section 2 — Data processing (derivatives computed, rationale)
  Section 3 — Pre-analysis visualization (chart + visual description)
  Section 4 — Correlation analysis (chart + peak finding + interpretation)
"""

from pathlib import Path
from datetime import datetime
import pandas as pd
import numpy as np
from .core import peak_correlation


def _format_sample(df: pd.DataFrame, n: int = 10) -> str:
    """Return a small markdown table of the first n rows of an aligned frame."""
    cols_to_show = ["x", "y", "x_d1", "y_d1"]
    available = [c for c in cols_to_show if c in df.columns]
    sample = df[available].head(n).round(2)
    return sample.to_markdown()


def write_report(pair, df: pd.DataFrame, lag_results: list,
                 pre_chart: Path, corr_chart: Path, out_path: Path) -> None:
    """Write a complete 4-section markdown report."""
    peak_lag, peak_r, peak_n = peak_correlation(lag_results)
    lag_str = f"{abs(peak_lag)} {pair.lag_unit}"
    direction = ("leading" if peak_lag > 0 else
                 "lagging" if peak_lag < 0 else
                 "coincident")

    date = df.index.min().date(), df.index.max().date()
    n_obs = len(df)

    lines = []
    lines.append(f"# {pair.name} — backtest report")
    lines.append("")
    lines.append(f"*Generated by `signal_tool` on {datetime.now().strftime('%Y-%m-%d')}*")
    lines.append("")
    lines.append(f"**Hypothesis:** {pair.hypothesis}")
    lines.append("")
    lines.append(f"**Headline result:** Peak correlation r = {peak_r:+.3f} at lag = {peak_lag:+d} {pair.lag_unit}")
    lines.append(f"({pair.leading.name} {direction} {pair.outcome.name} by {lag_str}, n={peak_n})")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 1
    lines.append("## Section 1 — Data Collection")
    lines.append("")
    lines.append(f"### Leading signal: `{pair.leading.name}`")
    lines.append(f"- Description: {pair.leading.description}")
    lines.append(f"- Source: {pair.leading.source_url}")
    lines.append(f"- Units: {pair.leading.units}")
    lines.append("")
    lines.append(f"### Outcome signal: `{pair.outcome.name}`")
    lines.append(f"- Description: {pair.outcome.description}")
    lines.append(f"- Source: {pair.outcome.source_url}")
    lines.append(f"- Units: {pair.outcome.units}")
    lines.append("")
    lines.append(f"### Aligned dataset")
    lines.append(f"- Frequency: {pair.frequency}")
    lines.append(f"- Range: {date[0]} to {date[1]}")
    lines.append(f"- Observations: {n_obs}")
    lines.append("")
    lines.append("First 10 rows of aligned (leading, outcome) data:")
    lines.append("")
    lines.append(_format_sample(df, n=10))
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 2
    lines.append("## Section 2 — Data Processing")
    lines.append("")
    lines.append("Transformations applied:")
    period = "12 months" if pair.frequency == "monthly" else "1 year"
    lines.append(f"- **1st derivative (YoY %)**: `(value[t] / value[t-{period}] - 1) * 100`. Why: normalizes both series to growth rates, comparable across different units and scales.")
    lines.append(f"- **2nd derivative (Δ YoY %)**: `yoy[t] - yoy[t-{period}]`. Why: reveals whether each series is *accelerating* or *decelerating* — often the cleanest place to spot inflection points.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 3
    lines.append("## Section 3 — Pre-analysis Visualization")
    lines.append("")
    lines.append(f"![Pre-analysis 3-panel chart]({pre_chart.name})")
    lines.append("")
    lines.append("**What's visible by eye:**")
    lines.append("- Top panel: levels of both series over time")
    lines.append("- Middle panel: 1st derivative (YoY %) — visible peaks and troughs in growth")
    lines.append("- Bottom panel: 2nd derivative — synchronized inflection points or divergences")
    lines.append("")
    lines.append(f"*Expected lead from hypothesis: {pair.expected_lead_low:.0f}–{pair.expected_lead_high:.0f} {pair.lag_unit}.*")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 4
    lines.append("## Section 4 — Correlation Analysis")
    lines.append("")
    lines.append(f"![Lag correlation chart]({corr_chart.name})")
    lines.append("")
    lines.append("### Correlation at each lag")
    lines.append("")
    lines.append(f"| Lag ({pair.lag_unit}) | r | n |")
    lines.append("|---|---|---|")
    for lag, r, n in lag_results:
        r_str = f"{r:+.3f}" if not np.isnan(r) else "—"
        marker = " ⭐" if lag == peak_lag else ""
        lines.append(f"| {lag:+d}{marker} | {r_str} | {n} |")
    lines.append("")
    lines.append("### Interpretation")
    lines.append("")
    in_range = pair.expected_lead_low <= abs(peak_lag) <= pair.expected_lead_high
    if abs(peak_r) >= 0.5 and peak_lag > 0 and in_range:
        verdict = "**Hypothesis CONFIRMED.** Strong positive correlation in predicted direction and within expected lead range."
    elif abs(peak_r) >= 0.4 and peak_lag > 0:
        verdict = "**Hypothesis PARTIALLY supported.** Moderate correlation in predicted direction; lead time may differ from hypothesis."
    elif abs(peak_r) < 0.3:
        verdict = "**Hypothesis REJECTED.** Correlation too weak to support a leading-indicator relationship at any tested lag."
    elif peak_lag < 0:
        verdict = "**Hypothesis REJECTED — direction reversed.** The outcome variable appears to lead the proposed leading signal, not the other way around."
    else:
        verdict = "**Hypothesis INCONCLUSIVE.** Mixed or weak signal across lags."
    lines.append(verdict)
    lines.append("")
    lines.append(f"Peak correlation: r = {peak_r:+.3f} at lag = {peak_lag:+d} {pair.lag_unit} (n={peak_n}).")
    lines.append("")

    out_path.write_text("\n".join(lines))
